using System.Diagnostics;

namespace dojo.leetcode;

public class Q193_ValidPhoneNumbersTestData : TestData
{
    protected override List<object[]> Data => 
    [
        [
            """
            987-123-4567
            123 456 7890
            (123) 456-7890
            0(001) 345-0000
            (001) 345-00001
            """,
            """
            987-123-4567
            (123) 456-7890
            """
        ]
    ];
}

public class Q193_ValidPhoneNumbersTests(ITestOutputHelper output) : TestBase(output)
{
    [Theory]
    [ClassData(typeof(Q193_ValidPhoneNumbersTestData))]
    public void Test(string input, string expected) 
    {
        File.WriteAllText("./file.txt", input.Trim());

        var sut = new Q193_ValidPhoneNumbers();
        var actual = Run(sut.Command);
        
        File.Delete("./file.txt");

        var expectedLines = expected.Trim().Split(Environment.NewLine);
        var actualLines = actual.Trim().Split(Environment.NewLine);

        foreach(var line in actualLines)
        {
            output.WriteLine(line);
            Assert.Contains(line, expectedLines);
        }
    }

    // Use "/bin/bash" for Linux/Mac, "cmd.exe" for Windows
    protected virtual string Shell => "/bin/bash";

    protected string Run(string command)
    {
        var processInfo = new ProcessStartInfo
        {
            FileName = Shell,
            Arguments = $"-c \"{command}\"",    // Replace "your command here" with your shell command
            UseShellExecute = false,            // Do not use OS shell, need to be false for RedirectStandardOutput set to true
            RedirectStandardOutput = true       // Any output, generated by a process is redirected back
        };

        string result = string.Empty;
        using (var process = Process.Start(processInfo))
        {
            // Read the output stream first and then wait.
            result = process!.StandardOutput.ReadToEnd();
            process.WaitForExit();

            // log the output
            output.WriteLine(result);
        }
        return result;
    }
}

public class Q193_ValidPhoneNumbers
{
    public string Command =>
    """
    cat file.txt | awk '/^([0-9]{3}-|\([0-9]{3}\) )[0-9]{3}-[0-9]{4}$/'
    """;
}